mailsac/mailsac-examples

LICENSE
README.md
conf.py
index.rst

Part of fix for https://github.com/ruffrey/mailsac-private/issues/227

Change business name

---

about/faq.rst
help/missing_mail.rst
index.rst
services/private_domains/private_domains.rst

Adds a help category to RTD and a section on missing mail. There have been several support requests regarding missing or delayed mail. This documentation is to address some of the common questions.

Where is my mail

---

services/sending_mail/sendingmail.rst

Call out which addresses a customer is allowed to send from.

Clarify which address can be sent from

---

README.md
services/catchall.rst
services/introduction.rst
services/mailstorage.rst
services/private_domains/private_domains.rst
services/sending_mail/sendingmail.rst

Bunch of small linting fixes.
Rewrote the majority of the message storage documentation to make it clear when messages are recycled. 
https://docs.mailsac.com/en/update_readme_local_build/services/mailstorage.html

Update readme local build

---

help/missing_mail.rst

Adds description of some of the sender limits encountered when sending email to mailsac.

Sender limits

---

about/introduction.rst
getting_started/checkmail.rst
services/forwarding/forwarding.rst
services/sending_mail/sendingmail.rst

- Removes REST from REST API since we have more than a REST API
- Fixes capitalization
- Fixes rst formatting warnings.

Remove rest from rest api

---

_static/.editorconfig
_static/custom.css
about/introduction.rst
api_examples/index.rst
services/forwarding/forwarding.rst
services/introduction.rst

- catch-all link was broken
- editorconfig added to prevent mismatched spacing, esp on CSS
- minor css tweak to use more complimentary sidebar color
- css to prevent screenshots from blending into background and being confusing

Minor fixes and css

---

help/account_management/account_management.rst
index.rst

Describes how to reset a password and request account deletion.

Add account management section

---

help/missing_mail.rst

Adds section about how and when to submit a whitelist request.

Add whitelist request section

---

services/message_storage/message_storage.rst

Fixes minor grammatical error.

Fix grammatical error

---

services/attachments.rst

Define attachment subheadings and subheadings.

Fix email attachment headings

---

.gitignore
README.md
conf.py

Python virtual environment makes it easier to isolate python
ennvironments. It ensures that user and system installed modules do not
conflict with one another. Shaving the yak.

Add support for python virtual envrionment

---

about/terms_of_service.rst

- Adds table of contents on the terms of service page
- fixes 1 misspelled word
- fixes formatting of lists
There were no changes made to the language in the terms of service. The changes were only markup changes.

Fix formatting

---

services/api_calls/api_calls.rst
services/custom_domains/custom_domains.rst

- Adds information about setting custom domains as public
- Adds details about api usage on custom domains set as public
- Minor tweaks to wording

Add public domain api call usage

---

services/message_storage/message_storage.rst

Adds a link and short description for the delete all messages by domain API route to the message storage section.

Add documentation for delete all message by domain api route

---

api_examples/download_all_inbox_attachments.rst
api_examples/getting_started/getting_started.rst
help/missing_mail.rst
services/attachments.rst
services/email_validation/email_validation.rst
services/forwarding/forwarding.rst
services/reading_mail/reading_mail.rst
services/sending_mail/sending_mail.rst
services/webhook/webhook.rst
services/websocket/websocket.rst

Update links to reflect the new URLs of API Documentation.

Update links to API documentation

---

help/account_management/account_management.rst
help/account_management/credential_management.rst
index.rst

Moves API/User Login documentation to a separate page.

Move API/User Login to discrete page

---

services/forwarding/forwarding.rst
services/mailredirect.rst

Screenshot of plus addressing section.

Add plus-addressing section

---

help/missing_mail.rst

- Changes missing mail section headers to be more descriptive of the contents in the section
- Remove custom domain section since it is duplicative of the information in the BYOD section
- Adds deny list section

Add deny list section

---

about/terms_of_service.rst
help/missing_mail.rst

Adds information for subscribers to send to private addresses or custom domains to avoid throttling.

Subscribers should send to private domains

---

about/terms_of_service.rst

Sending of email from mailsac is no longer supported.

Remove terms related to sending
